"""Register the Soundcheck workforce on Band and write agent_config.yaml.

Idempotent-ish: skips names that already exist on the account (their keys can't be
re-fetched — the API shows a key once; regenerate from the Band UI if lost).

Usage:  .venv/Scripts/python scripts/register_agents.py
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

import yaml
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))
load_dotenv(ROOT / ".env")

from app.band_human import BandHuman  # noqa: E402

# Naming rule (spec §4.1): never "Agent/Bot/Assistant" alone — but descriptive
# compounds like "Code Scanner" are fine. Keep names distinct and instrument-like.
WORKFORCE: dict[str, tuple[str, str]] = {
    "scout": (
        "Scout",
        "Ingests the connected repo and site to build OrgContext: stack, domain, "
        "data sensitivity, suggested compliance frameworks.",
    ),
    "bandleader": (
        "Bandleader",
        "The concertmaster. Plans the run, recruits the right specialists, sequences "
        "the audit, posts the visible Plan, and routes work via @mentions.",
    ),
    "code_scanner": (
        "Code Scanner",
        "Static analysis (semgrep). Finds insecure code patterns and writes Finding "
        "memories with evidence and reasoning.",
    ),
    "dependencies": (
        "Dependency Auditor",
        "Audits dependencies (pip-audit/npm audit/trivy) for known vulnerabilities "
        "and writes Finding memories.",
    ),
    "secrets_config": (
        "Secrets Sentinel",
        "Scans for committed secrets and unsafe configuration (gitleaks/trufflehog). "
        "All evidence is redacted — never echoes a discovered secret.",
    ),
    "compliance_mapper": (
        "Compliance Mapper",
        "Maps Findings to compliance controls (SOC 2, ISO 27001) and writes "
        "ControlMapping memories linked to their Findings.",
    ),
    "fixer": (
        "Fixer",
        "Proposes patches for eligible findings (high confidence, low risk only) on a "
        "branch. Defensive remediation only; never merges without human approval.",
    ),
    "reviewer": (
        "Reviewer",
        "Reviews proposed patches with a different model than the Fixer. Writes "
        "ReviewResult memories; requests revisions until the diff is sound.",
    ),
}

CONFIG_PATH = ROOT / "agent_config.yaml"


async def main() -> None:
    human = BandHuman()
    existing_cfg: dict = {}
    if CONFIG_PATH.exists():
        existing_cfg = yaml.safe_load(CONFIG_PATH.read_text()) or {}

    existing_agents = {a["name"]: a for a in await human.list_agents(page_size=100)}
    print(f"Account has {len(existing_agents)} agents already registered.")

    created, skipped = 0, 0
    for key, (name, description) in WORKFORCE.items():
        if key in existing_cfg and existing_cfg[key].get("api_key", "").strip("<>"):
            print(f"  = {name}: already in agent_config.yaml — keeping")
            skipped += 1
            continue
        if name in existing_agents:
            print(
                f"  ! {name}: exists on Band but no key in agent_config.yaml — "
                f"regenerate its key in the Band UI (id {existing_agents[name]['id']})"
            )
            skipped += 1
            continue
        data = await human.register_agent(name, description)
        agent = data["agent"]
        existing_cfg[key] = {
            "agent_id": agent["id"],
            "api_key": data["credentials"]["api_key"],
        }
        print(f"  + {name}: registered ({agent['id']})")
        created += 1

    CONFIG_PATH.write_text(
        "# Band agent credentials — generated by scripts/register_agents.py. NEVER COMMIT.\n"
        + yaml.safe_dump(existing_cfg, sort_keys=False),
        encoding="utf-8",
    )
    await human.aclose()
    print(f"\nDone: {created} registered, {skipped} skipped -> {CONFIG_PATH.name}")


if __name__ == "__main__":
    asyncio.run(main())
